### ISSUE TITLE
soft reset & hard reset

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#14]
Soft Reset is simply powering off and on - no data is lost

Hard Reset is forcibly stopping the power - data is lost

**Comment by SupernaviX** [comment]
@AngelofMe not totally sure how that could work. The virtual boy "saves your game" by writing to a special part of the cartridge during normal gameplay; there isn't really a save process to shut down the system around.

Would it solve this if I added an option to disable persistent SRAM? so that every time you opened the game it was as if you were opening it for the first time? Or maybe a "clear sram" option?
