### ISSUE TITLE
Polling or Callback?

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#34]
https://www.yoctopuce.com/EN/article/polling-vs-callback

**Comment by SupernaviX** [comment]
Both, actually!

I guess it's more accurate to say "callback"; the frontend will [call a function](https://github.com/SupernaviX/vvb/blob/main/app/src/main/java/com/simongellis/vvb/emulator/Controller.kt#L44-L49) with a 16-bit [bitmask](https://en.wikipedia.org/wiki/Mask_(computing)) describing which buttons are pressed. That function [stores the bitmask](https://github.com/SupernaviX/vvb/blob/main/src/controller.rs#L48) in a place that the backend can read it. Android strongly encourages callback style, because it keeps the phone responsive while the app waits for input.

But to the emulated games themselves, it's "polling", because that's how the real Virtual Boy works. The game [writes to a specific memory location](https://files.virtual-boy.com/download/978651/stsvb.html#game_pad_control), and the emulator (or real Virtual Boy) will [start a process](https://github.com/SupernaviX/vvb/blob/main/src/emulator/hardware.rs#L137-L140) that ends with [storing that bitmask](https://github.com/SupernaviX/vvb/blob/main/src/emulator/hardware.rs#L260-L274) in [the memory location where it belongs](https://files.virtual-boy.com/download/978651/stsvb.html#game_pad_data_registers).

**Comment by AngelofMe** [comment]
Thanks for explaining so much
Although I do not understand these knowledge
