### ISSUE TITLE
drivers and high/low level emulation?

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#41]
video: gl, vulkan
audio: opensl, rsound
audio resampler: sinc, cc

it's low level emulation?

**Comment by AngelofMe** [comment]
Another question
State and Save file path?

**Comment by SupernaviX** [comment]
I don't really understand the question(s?)

I think this is high-level emulation, since it's simulating what the hardware did instead of simulating the hardware. But I don't really know.

State and save files are saved in `/data/data/com.simongellis.vvb/files`, the directory Android made. [This](https://developer.android.com/training/data-storage/app-specific) describes more about it.
